name: dimo-labeling
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - imageio
      - numpy
      - opencv-contrib-python
      - pillow
      - scipy
      - pyyaml
      - matplotlib
      - scikit-image
      - flask
      - flask_cors
